Require Export UniMath.Algebra.Monoids.
Require Export UniMath.Algebra.RigsAndRings.
Require Import UniMath.MoreFoundations.All.

(* Monoid generated by a subset *)
Definition monoid_gen (X : monoid) (S : hsubtype X) : submonoid X :=
  submonoidpair (subtype_intersection
                   (λ (B : ∑ (C : submonoid X), ∏ (x : X), C x), pr1 B))
                (intersection_submonoid _
                (λ B, pr2 (pr1 B))).

(* Localization at a subset *)
Definition abmonoid_loc (X : abmonoid) (S : hsubtype X) : abmonoid :=
  abmonoidfrac X (monoid_gen X S).

Open Scope rig_scope.

(* It turns out the things below have already been done in RigsandRings.v, so it should be deleted.
   There, it's called "ring of fractions", not "localization" *)

(* Induced additive structure on localization of a rig *)
Definition addition_of_localization (X : commrig) (S : submonoid (commrigmultabmonoid X)) : binop (X × S) :=
  λ rs tu, dirprodpair (pr1 rs * pr2 tu + pr1 tu * pr2 rs) (pr2 rs * pr2 tu).

Definition addition_on_localization (X : commrig) (S : hsubtype X) :
  binop (abmonoid_loc (commrigmultabmonoid X) S).
Proof.
